# Based on https://github.com/frezbo/dockerfiles/blob/main/.github/workflows/ci.yml
name: Build and Publish Docker image
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get matrix 
        id: set-matrix
        run: echo matrix=$(cat $GITHUB_WORKSPACE/containers.json) >> $GITHUB_OUTPUT
  log-metadata:
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - name: log
        run: echo ${{needs.metadata.outputs.matrix}}
      - name: log json
        run: echo ${{ fromJson(needs.metadata.outputs.matrix) }}
  docker:
    runs-on: ubuntu-latest
    needs: metadata
    strategy:
      matrix: ${{ fromJson(needs.metadata.outputs.matrix) }}
    steps:
      - name: log
        run: echo ${{ matrix }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Login to GHCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v4.3.0
      #   with:
      #     images: ghcr.io/tomcranitch/${{ matrix.name }}
      #     flavor: |
      #       latest=false
      #     tags: |
      #       type=raw,enable=true,value=${{ matrix.version }}
      #     labels: |
      #       org.opencontainers.image.version=${{ matrix.version }}
      - name: Build container
        id: release
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.path }}/Dockerfile
          labels: |-
            ${{ steps.vars.outputs.chan_label_type }}.created="${{ steps.vars.outputs.chan_build_date }}"
            ${{ steps.vars.outputs.chan_label_type }}.title="${{ matrix.name }}"
            ${{ steps.vars.outputs.chan_label_type }}.version="${{ matrix.version }}"
            ${{ steps.vars.outputs.chan_label_type }}.authors="Tom Cranitch"
            ${{ steps.vars.outputs.chan_label_type }}.url="https://github.com/tomcranitch/containers/${{ matrix.path }}"
            ${{ steps.vars.outputs.chan_label_type }}.build.url="https://github.com/tomcranitch/containers/actions/runs/${{ github.run_id }}"
            ${{ steps.vars.outputs.chan_label_type }}.documentation="https://github.com/tomcranitch/containers/${{ matrix.path }}/README.md"
            ${{ steps.vars.outputs.chan_label_type }}.revision="${{ github.sha }}"
          platforms: "linux/amd64"
          push: ${{ inputs.pushImages == 'true' }}
          tags: |-
            ghcr.io/tomcranitch/${{ matrix.name }}:latest
            ghcr.io/tomcranitch/${{ matrix.name }}:${{ matrix.version }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
